// Autogenerated, do not edit. All changes will be undone.

package com.sapphire.items;

import com.sapphire.armor.FlashArmor;
import com.sapphire.armor.FutureFlashArmor;
import com.sapphire.handlers.CreativeTabHandler;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class FlashItems
{
	public static int flashDurability = 72;
	
	public static ItemArmor.ArmorMaterial enumArmorMaterialFlash = EnumHelper
			.addArmorMaterial("FLASH", "flash", flashDurability, new int[] { 0, 0, 0, 0 }, 0);
	@Mod.Metadata public static ModMetadata meta;
	public static Item helmetFlash;
	
	// public static Item flashRing;
	// public static Item flashRingOn;
	public static Item chestPlateFlash;
	public static Item legsFlash;
	public static Item bootsFlash;
	public static Item helmetFutureFlash;
	public static Item chestPlateFutureFlash;
	public static Item legsFutureFlash;
	public static Item bootsFutureFlash;

	public static void mainRegistry()
	{
		initItems();
		registerItems();
	}

	public static void initItems()
	{
		//RenderingRegistry.addNewArmourRendererPrefix("5");
		
		// flashRing = new
		// ItemFlashRing("flashRing").setUnlocalizedName("flashRing");
		// flashRingOn = new
		// ItemFlashRingOn("flashRingOn").setUnlocalizedName("flashRingOn");

		helmetFlash = new FlashArmor(enumArmorMaterialFlash, 5, 0).setUnlocalizedName("helmetFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);
		chestPlateFlash = new FlashArmor(enumArmorMaterialFlash, 5, 1).setUnlocalizedName("chestFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);
		legsFlash = new FlashArmor(enumArmorMaterialFlash, 5, 2).setUnlocalizedName("legsFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);
		bootsFlash = new FlashArmor(enumArmorMaterialFlash, 5, 3).setUnlocalizedName("bootsFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);

		helmetFutureFlash = new FutureFlashArmor(enumArmorMaterialFlash, 5, 0).setUnlocalizedName("helmetFutureFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);
		chestPlateFutureFlash = new FutureFlashArmor(enumArmorMaterialFlash, 5, 1)
				.setUnlocalizedName("chestFutureFlash").setCreativeTab(CreativeTabHandler.tabFlash);
		legsFutureFlash = new FutureFlashArmor(enumArmorMaterialFlash, 5, 2).setUnlocalizedName("legsFutureFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);
		bootsFutureFlash = new FutureFlashArmor(enumArmorMaterialFlash, 5, 3).setUnlocalizedName("bootsFutureFlash")
				.setCreativeTab(CreativeTabHandler.tabFlash);
	}
	
	public static void registerItems()
	{
		// GameRegistry.registerItem(flashRing,
		// flashRing.getUnlocalizedName().substring(5));
		// GameRegistry.registerItem(flashRingOn,
		// flashRingOn.getUnlocalizedName().substring(5));
		
		GameRegistry.registerItem(helmetFlash, helmetFlash.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(chestPlateFlash, chestPlateFlash.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(legsFlash, legsFlash.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(bootsFlash, bootsFlash.getUnlocalizedName().substring(5));

		GameRegistry.registerItem(helmetFutureFlash, helmetFutureFlash.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(chestPlateFutureFlash, chestPlateFutureFlash.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(legsFutureFlash, legsFutureFlash.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(bootsFutureFlash, bootsFutureFlash.getUnlocalizedName().substring(5));
	}
}
